### ISSUE TITLE
[BUG] Blank screen visible on Books Details page

### ISSUE THREAD

**Issue by cacianod** [kunalashar25/wq2024-BuildingAutomationFramework#5]
**Describe the bug**
After click on Programming JavaScript Application, the page does not load.

**To Reproduce**
1. Go to 'httsd://demoqa.com/login' 
2. Login with user # wq-basic and password # Wq-basic&01
3. Click on Book Store Application tab to the left and select Book Store
4. In the search bar , search for # Programming JavaScript Application
5. Click on the result 
6. See error - A plain white page is shown to user.

**Expected behavior**
The page should load showing the book (element) Programming JavaScript Application 

**Screenshots**
![image](https://github.com/kunalashar25/wq2024_building_automation_framework/assets/66372865/c8da9874-a4c0-4094-a119-d68b364df788)
![Capture](https://github.com/kunalashar25/wq2024_building_automation_framework/assets/66372865/8ad65113-8201-460a-8bfb-f3645e8624ec)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Win 10
 - Browser [e.g. chrome, safari] - Chrome
 - Version [e.g. 22] - 121.0.6167.185

**Additional context**
Error URL - https://demoqa.com/books?book=9781491950296

**Comment by kunalashar25** [comment]
Hi @cacianod 

Thanks for reporting it. This is an application-specific issue and I'm unable to resolve it from my end.

For now, script failures are expected and they won't impact our session. I have added a comment on the [linkedIn post](https://www.linkedin.com/posts/thetesttribe_build-automation-framework-from-scratch-activity-7150713573629943810-DEZj) as well.

Let me know if this helps.
